# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import storage_pb2 as storage__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDatabase = channel.unary_unary(
                '/storage.StorageService/CreateDatabase',
                request_serializer=storage__pb2.DbReq.SerializeToString,
                response_deserializer=storage__pb2.RecordResponse.FromString,
                _registered_method=True)
        self.ListDatabases = channel.unary_unary(
                '/storage.StorageService/ListDatabases',
                request_serializer=storage__pb2.EmptyReq.SerializeToString,
                response_deserializer=storage__pb2.ListRes.FromString,
                _registered_method=True)
        self.DeleteDatabase = channel.unary_unary(
                '/storage.StorageService/DeleteDatabase',
                request_serializer=storage__pb2.DbReq.SerializeToString,
                response_deserializer=storage__pb2.RecordResponse.FromString,
                _registered_method=True)
        self.CreateTable = channel.unary_unary(
                '/storage.StorageService/CreateTable',
                request_serializer=storage__pb2.TableReq.SerializeToString,
                response_deserializer=storage__pb2.RecordResponse.FromString,
                _registered_method=True)
        self.ListTables = channel.unary_unary(
                '/storage.StorageService/ListTables',
                request_serializer=storage__pb2.DbReq.SerializeToString,
                response_deserializer=storage__pb2.ListRes.FromString,
                _registered_method=True)
        self.DeleteTable = channel.unary_unary(
                '/storage.StorageService/DeleteTable',
                request_serializer=storage__pb2.TableReq.SerializeToString,
                response_deserializer=storage__pb2.RecordResponse.FromString,
                _registered_method=True)
        self.InsertRecord = channel.unary_unary(
                '/storage.StorageService/InsertRecord',
                request_serializer=storage__pb2.InsertRequest.SerializeToString,
                response_deserializer=storage__pb2.RecordResponse.FromString,
                _registered_method=True)
        self.FindRecords = channel.unary_unary(
                '/storage.StorageService/FindRecords',
                request_serializer=storage__pb2.SearchRequest.SerializeToString,
                response_deserializer=storage__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.UpdateRecords = channel.unary_unary(
                '/storage.StorageService/UpdateRecords',
                request_serializer=storage__pb2.UpdateRequest.SerializeToString,
                response_deserializer=storage__pb2.RecordResponse.FromString,
                _registered_method=True)
        self.DeleteRecords = channel.unary_unary(
                '/storage.StorageService/DeleteRecords',
                request_serializer=storage__pb2.DeleteRequest.SerializeToString,
                response_deserializer=storage__pb2.RecordResponse.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDatabase(self, request, context):
        """Administración
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatabases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertRecord(self, request, context):
        """Operaciones CRUD
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDatabase,
                    request_deserializer=storage__pb2.DbReq.FromString,
                    response_serializer=storage__pb2.RecordResponse.SerializeToString,
            ),
            'ListDatabases': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatabases,
                    request_deserializer=storage__pb2.EmptyReq.FromString,
                    response_serializer=storage__pb2.ListRes.SerializeToString,
            ),
            'DeleteDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDatabase,
                    request_deserializer=storage__pb2.DbReq.FromString,
                    response_serializer=storage__pb2.RecordResponse.SerializeToString,
            ),
            'CreateTable': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTable,
                    request_deserializer=storage__pb2.TableReq.FromString,
                    response_serializer=storage__pb2.RecordResponse.SerializeToString,
            ),
            'ListTables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTables,
                    request_deserializer=storage__pb2.DbReq.FromString,
                    response_serializer=storage__pb2.ListRes.SerializeToString,
            ),
            'DeleteTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTable,
                    request_deserializer=storage__pb2.TableReq.FromString,
                    response_serializer=storage__pb2.RecordResponse.SerializeToString,
            ),
            'InsertRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertRecord,
                    request_deserializer=storage__pb2.InsertRequest.FromString,
                    response_serializer=storage__pb2.RecordResponse.SerializeToString,
            ),
            'FindRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.FindRecords,
                    request_deserializer=storage__pb2.SearchRequest.FromString,
                    response_serializer=storage__pb2.SearchResponse.SerializeToString,
            ),
            'UpdateRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRecords,
                    request_deserializer=storage__pb2.UpdateRequest.FromString,
                    response_serializer=storage__pb2.RecordResponse.SerializeToString,
            ),
            'DeleteRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecords,
                    request_deserializer=storage__pb2.DeleteRequest.FromString,
                    response_serializer=storage__pb2.RecordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storage.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/CreateDatabase',
            storage__pb2.DbReq.SerializeToString,
            storage__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatabases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/ListDatabases',
            storage__pb2.EmptyReq.SerializeToString,
            storage__pb2.ListRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/DeleteDatabase',
            storage__pb2.DbReq.SerializeToString,
            storage__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/CreateTable',
            storage__pb2.TableReq.SerializeToString,
            storage__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/ListTables',
            storage__pb2.DbReq.SerializeToString,
            storage__pb2.ListRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/DeleteTable',
            storage__pb2.TableReq.SerializeToString,
            storage__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/InsertRecord',
            storage__pb2.InsertRequest.SerializeToString,
            storage__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/FindRecords',
            storage__pb2.SearchRequest.SerializeToString,
            storage__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/UpdateRecords',
            storage__pb2.UpdateRequest.SerializeToString,
            storage__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/DeleteRecords',
            storage__pb2.DeleteRequest.SerializeToString,
            storage__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
