# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agregacion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agregacion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61gregacion.proto\x12\nagregacion\"H\n\x12PeticionAgregacion\x12\x11\n\toperacion\x18\x01 \x01(\t\x12\x10\n\x08\x64\x62_tabla\x18\x02 \x01(\t\x12\r\n\x05\x63\x61mpo\x18\x03 \x01(\t\"H\n\x13RespuestaAgregacion\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x11\n\tresultado\x18\x02 \x01(\t\x12\x0f\n\x07mensaje\x18\x03 \x01(\t2a\n\x12ServicioAgregacion\x12K\n\x08\x43\x61lcular\x12\x1e.agregacion.PeticionAgregacion\x1a\x1f.agregacion.RespuestaAgregacionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agregacion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PETICIONAGREGACION']._serialized_start=32
  _globals['_PETICIONAGREGACION']._serialized_end=104
  _globals['_RESPUESTAAGREGACION']._serialized_start=106
  _globals['_RESPUESTAAGREGACION']._serialized_end=178
  _globals['_SERVICIOAGREGACION']._serialized_start=180
  _globals['_SERVICIOAGREGACION']._serialized_end=277
# @@protoc_insertion_point(module_scope)
