# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: base_datos.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'base_datos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61se_datos.proto\x12\nbase_datos\"E\n\x10PeticionConsulta\x12\r\n\x05tabla\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63\x63ion\x18\x02 \x01(\t\x12\x12\n\ndatos_json\x18\x03 \x01(\t\"F\n\x11RespuestaConsulta\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x11\n\tresultado\x18\x03 \x01(\t2i\n\x16ServicioAlmacenamiento\x12O\n\x10\x45jecutarConsulta\x12\x1c.base_datos.PeticionConsulta\x1a\x1d.base_datos.RespuestaConsultab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_datos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PETICIONCONSULTA']._serialized_start=32
  _globals['_PETICIONCONSULTA']._serialized_end=101
  _globals['_RESPUESTACONSULTA']._serialized_start=103
  _globals['_RESPUESTACONSULTA']._serialized_end=173
  _globals['_SERVICIOALMACENAMIENTO']._serialized_start=175
  _globals['_SERVICIOALMACENAMIENTO']._serialized_end=280
# @@protoc_insertion_point(module_scope)
