# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import base_datos_pb2 as base__datos__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in base_datos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicioAlmacenamientoStub(object):
    """Definimos el servicio y sus funciones
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EjecutarConsulta = channel.unary_unary(
                '/base_datos.ServicioAlmacenamiento/EjecutarConsulta',
                request_serializer=base__datos__pb2.PeticionConsulta.SerializeToString,
                response_deserializer=base__datos__pb2.RespuestaConsulta.FromString,
                _registered_method=True)


class ServicioAlmacenamientoServicer(object):
    """Definimos el servicio y sus funciones
    """

    def EjecutarConsulta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicioAlmacenamientoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EjecutarConsulta': grpc.unary_unary_rpc_method_handler(
                    servicer.EjecutarConsulta,
                    request_deserializer=base__datos__pb2.PeticionConsulta.FromString,
                    response_serializer=base__datos__pb2.RespuestaConsulta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'base_datos.ServicioAlmacenamiento', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('base_datos.ServicioAlmacenamiento', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicioAlmacenamiento(object):
    """Definimos el servicio y sus funciones
    """

    @staticmethod
    def EjecutarConsulta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/base_datos.ServicioAlmacenamiento/EjecutarConsulta',
            base__datos__pb2.PeticionConsulta.SerializeToString,
            base__datos__pb2.RespuestaConsulta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
