# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import orquestador_pb2 as orquestador__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orquestador_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicioOrquestadorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/orquestador.ServicioOrquestador/Login',
                request_serializer=orquestador__pb2.PeticionLoginOrquestador.SerializeToString,
                response_deserializer=orquestador__pb2.RespuestaLoginOrquestador.FromString,
                _registered_method=True)
        self.Registro = channel.unary_unary(
                '/orquestador.ServicioOrquestador/Registro',
                request_serializer=orquestador__pb2.PeticionRegistroOrquestador.SerializeToString,
                response_deserializer=orquestador__pb2.RespuestaRegistroOrquestador.FromString,
                _registered_method=True)
        self.EnviarComando = channel.unary_unary(
                '/orquestador.ServicioOrquestador/EnviarComando',
                request_serializer=orquestador__pb2.PeticionComandoOrquestador.SerializeToString,
                response_deserializer=orquestador__pb2.RespuestaComandoOrquestador.FromString,
                _registered_method=True)


class ServicioOrquestadorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Registro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarComando(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicioOrquestadorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=orquestador__pb2.PeticionLoginOrquestador.FromString,
                    response_serializer=orquestador__pb2.RespuestaLoginOrquestador.SerializeToString,
            ),
            'Registro': grpc.unary_unary_rpc_method_handler(
                    servicer.Registro,
                    request_deserializer=orquestador__pb2.PeticionRegistroOrquestador.FromString,
                    response_serializer=orquestador__pb2.RespuestaRegistroOrquestador.SerializeToString,
            ),
            'EnviarComando': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarComando,
                    request_deserializer=orquestador__pb2.PeticionComandoOrquestador.FromString,
                    response_serializer=orquestador__pb2.RespuestaComandoOrquestador.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orquestador.ServicioOrquestador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orquestador.ServicioOrquestador', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicioOrquestador(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orquestador.ServicioOrquestador/Login',
            orquestador__pb2.PeticionLoginOrquestador.SerializeToString,
            orquestador__pb2.RespuestaLoginOrquestador.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Registro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orquestador.ServicioOrquestador/Registro',
            orquestador__pb2.PeticionRegistroOrquestador.SerializeToString,
            orquestador__pb2.RespuestaRegistroOrquestador.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnviarComando(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orquestador.ServicioOrquestador/EnviarComando',
            orquestador__pb2.PeticionComandoOrquestador.SerializeToString,
            orquestador__pb2.RespuestaComandoOrquestador.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
