# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orquestador.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orquestador.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11orquestador.proto\x12\x0borquestador\"=\n\x18PeticionLoginOrquestador\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"W\n\x19RespuestaLoginOrquestador\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0b\n\x03rol\x18\x03 \x01(\t\x12\x0f\n\x07mensaje\x18\x04 \x01(\t\"^\n\x1bPeticionRegistroOrquestador\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0b\n\x03rol\x18\x03 \x01(\t\x12\x0f\n\x07\x63reador\x18\x04 \x01(\t\">\n\x1cRespuestaRegistroOrquestador\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"J\n\x1aPeticionComandoOrquestador\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\x0f\n\x07\x63omando\x18\x03 \x01(\t\"P\n\x1bRespuestaComandoOrquestador\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x11\n\tresultado\x18\x03 \x01(\t2\xb2\x02\n\x13ServicioOrquestador\x12V\n\x05Login\x12%.orquestador.PeticionLoginOrquestador\x1a&.orquestador.RespuestaLoginOrquestador\x12_\n\x08Registro\x12(.orquestador.PeticionRegistroOrquestador\x1a).orquestador.RespuestaRegistroOrquestador\x12\x62\n\rEnviarComando\x12\'.orquestador.PeticionComandoOrquestador\x1a(.orquestador.RespuestaComandoOrquestadorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orquestador_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PETICIONLOGINORQUESTADOR']._serialized_start=34
  _globals['_PETICIONLOGINORQUESTADOR']._serialized_end=95
  _globals['_RESPUESTALOGINORQUESTADOR']._serialized_start=97
  _globals['_RESPUESTALOGINORQUESTADOR']._serialized_end=184
  _globals['_PETICIONREGISTROORQUESTADOR']._serialized_start=186
  _globals['_PETICIONREGISTROORQUESTADOR']._serialized_end=280
  _globals['_RESPUESTAREGISTROORQUESTADOR']._serialized_start=282
  _globals['_RESPUESTAREGISTROORQUESTADOR']._serialized_end=344
  _globals['_PETICIONCOMANDOORQUESTADOR']._serialized_start=346
  _globals['_PETICIONCOMANDOORQUESTADOR']._serialized_end=420
  _globals['_RESPUESTACOMANDOORQUESTADOR']._serialized_start=422
  _globals['_RESPUESTACOMANDOORQUESTADOR']._serialized_end=502
  _globals['_SERVICIOORQUESTADOR']._serialized_start=505
  _globals['_SERVICIOORQUESTADOR']._serialized_end=811
# @@protoc_insertion_point(module_scope)
