# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: puerta_enlace.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'puerta_enlace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13puerta_enlace.proto\x12\rpuerta_enlace\"9\n\x14PeticionLoginGateway\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"S\n\x15RespuestaLoginGateway\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0b\n\x03rol\x18\x03 \x01(\t\x12\x0f\n\x07mensaje\x18\x04 \x01(\t\"Z\n\x17PeticionRegistroGateway\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0b\n\x03rol\x18\x03 \x01(\t\x12\x0f\n\x07\x63reador\x18\x04 \x01(\t\":\n\x18RespuestaRegistroGateway\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"F\n\x16PeticionComandoGateway\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\x0f\n\x07\x63omando\x18\x03 \x01(\t\"L\n\x17RespuestaComandoGateway\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x11\n\tresultado\x18\x03 \x01(\t2\xa2\x02\n\x0fServicioGateway\x12R\n\x05Login\x12#.puerta_enlace.PeticionLoginGateway\x1a$.puerta_enlace.RespuestaLoginGateway\x12[\n\x08Registro\x12&.puerta_enlace.PeticionRegistroGateway\x1a\'.puerta_enlace.RespuestaRegistroGateway\x12^\n\rEnviarComando\x12%.puerta_enlace.PeticionComandoGateway\x1a&.puerta_enlace.RespuestaComandoGatewayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'puerta_enlace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PETICIONLOGINGATEWAY']._serialized_start=38
  _globals['_PETICIONLOGINGATEWAY']._serialized_end=95
  _globals['_RESPUESTALOGINGATEWAY']._serialized_start=97
  _globals['_RESPUESTALOGINGATEWAY']._serialized_end=180
  _globals['_PETICIONREGISTROGATEWAY']._serialized_start=182
  _globals['_PETICIONREGISTROGATEWAY']._serialized_end=272
  _globals['_RESPUESTAREGISTROGATEWAY']._serialized_start=274
  _globals['_RESPUESTAREGISTROGATEWAY']._serialized_end=332
  _globals['_PETICIONCOMANDOGATEWAY']._serialized_start=334
  _globals['_PETICIONCOMANDOGATEWAY']._serialized_end=404
  _globals['_RESPUESTACOMANDOGATEWAY']._serialized_start=406
  _globals['_RESPUESTACOMANDOGATEWAY']._serialized_end=482
  _globals['_SERVICIOGATEWAY']._serialized_start=485
  _globals['_SERVICIOGATEWAY']._serialized_end=775
# @@protoc_insertion_point(module_scope)
