# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: seguridad.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'seguridad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fseguridad.proto\x12\tseguridad\"2\n\rPeticionLogin\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"?\n\x0eRespuestaToken\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0f\n\x07mensaje\x18\x03 \x01(\t\"#\n\x12PeticionValidacion\x12\r\n\x05token\x18\x01 \x01(\t\"C\n\x13RespuestaValidacion\x12\x0e\n\x06valido\x18\x01 \x01(\x08\x12\x0b\n\x03rol\x18\x02 \x01(\t\x12\x0f\n\x07usuario\x18\x03 \x01(\t\"S\n\x10PeticionRegistro\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0b\n\x03rol\x18\x03 \x01(\t\x12\x0f\n\x07\x63reador\x18\x04 \x01(\t\"3\n\x11RespuestaRegistro\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2\xf7\x01\n\x11ServicioSeguridad\x12\x44\n\rIniciarSesion\x12\x18.seguridad.PeticionLogin\x1a\x19.seguridad.RespuestaToken\x12M\n\x0cValidarToken\x12\x1d.seguridad.PeticionValidacion\x1a\x1e.seguridad.RespuestaValidacion\x12M\n\x10RegistrarUsuario\x12\x1b.seguridad.PeticionRegistro\x1a\x1c.seguridad.RespuestaRegistrob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seguridad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PETICIONLOGIN']._serialized_start=30
  _globals['_PETICIONLOGIN']._serialized_end=80
  _globals['_RESPUESTATOKEN']._serialized_start=82
  _globals['_RESPUESTATOKEN']._serialized_end=145
  _globals['_PETICIONVALIDACION']._serialized_start=147
  _globals['_PETICIONVALIDACION']._serialized_end=182
  _globals['_RESPUESTAVALIDACION']._serialized_start=184
  _globals['_RESPUESTAVALIDACION']._serialized_end=251
  _globals['_PETICIONREGISTRO']._serialized_start=253
  _globals['_PETICIONREGISTRO']._serialized_end=336
  _globals['_RESPUESTAREGISTRO']._serialized_start=338
  _globals['_RESPUESTAREGISTRO']._serialized_end=389
  _globals['_SERVICIOSEGURIDAD']._serialized_start=392
  _globals['_SERVICIOSEGURIDAD']._serialized_end=639
# @@protoc_insertion_point(module_scope)
