# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import seguridad_pb2 as seguridad__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in seguridad_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicioSeguridadStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IniciarSesion = channel.unary_unary(
                '/seguridad.ServicioSeguridad/IniciarSesion',
                request_serializer=seguridad__pb2.PeticionLogin.SerializeToString,
                response_deserializer=seguridad__pb2.RespuestaToken.FromString,
                _registered_method=True)
        self.ValidarToken = channel.unary_unary(
                '/seguridad.ServicioSeguridad/ValidarToken',
                request_serializer=seguridad__pb2.PeticionValidacion.SerializeToString,
                response_deserializer=seguridad__pb2.RespuestaValidacion.FromString,
                _registered_method=True)
        self.RegistrarUsuario = channel.unary_unary(
                '/seguridad.ServicioSeguridad/RegistrarUsuario',
                request_serializer=seguridad__pb2.PeticionRegistro.SerializeToString,
                response_deserializer=seguridad__pb2.RespuestaRegistro.FromString,
                _registered_method=True)


class ServicioSeguridadServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IniciarSesion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidarToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistrarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicioSeguridadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IniciarSesion': grpc.unary_unary_rpc_method_handler(
                    servicer.IniciarSesion,
                    request_deserializer=seguridad__pb2.PeticionLogin.FromString,
                    response_serializer=seguridad__pb2.RespuestaToken.SerializeToString,
            ),
            'ValidarToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidarToken,
                    request_deserializer=seguridad__pb2.PeticionValidacion.FromString,
                    response_serializer=seguridad__pb2.RespuestaValidacion.SerializeToString,
            ),
            'RegistrarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarUsuario,
                    request_deserializer=seguridad__pb2.PeticionRegistro.FromString,
                    response_serializer=seguridad__pb2.RespuestaRegistro.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seguridad.ServicioSeguridad', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('seguridad.ServicioSeguridad', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicioSeguridad(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IniciarSesion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seguridad.ServicioSeguridad/IniciarSesion',
            seguridad__pb2.PeticionLogin.SerializeToString,
            seguridad__pb2.RespuestaToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidarToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seguridad.ServicioSeguridad/ValidarToken',
            seguridad__pb2.PeticionValidacion.SerializeToString,
            seguridad__pb2.RespuestaValidacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistrarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seguridad.ServicioSeguridad/RegistrarUsuario',
            seguridad__pb2.PeticionRegistro.SerializeToString,
            seguridad__pb2.RespuestaRegistro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
